version: "3"

services:
  parrot:
    image: parrotsec/security:latest
    container_name: parrot
    hostname: parrot
    networks:
      vulnerableNet:
        ipv4_address: 172.16.20.20
    devices:
      - /dev/snd
      - /dev/dri
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
    tty: true
    stdin_open: true

#    restart: unless-stopped

  metasploit:
    image: tleemcjr/metasploitable2
    container_name: metasploitable
    hostname: metasploitable2
    networks:
      vulnerableNet:
        ipv4_address: 172.16.20.100
    command: /bin/bash
    tty: true
    stdin_open: true
#    restart: unless-stopped

  dvwa:
    image: vulnerables/web-dvwa
    container_name: web-dvwa
    hostname: web-dvwa
    networks:
      vulnerableNet:
        ipv4_address: 172.16.20.120
    ports:
      - 80:80
    command: bash
    restart: unless-stopped

  mutillidae:
    image: szsecurity/mutillidae
    container_name: mutillidae
    hostname: mutillidae
    networks:
      vulnerableNet:
        ipv4_address: 172.16.20.130
    ports:
      - 1337:80
    command: bash -c "/etc/init.d/mysql start && /usr/sbin/apache2ctl -D FOREGROUND"
#    restart: unless-stopped

  webgoat:
    image: webgoat/webgoat
    container_name: webgoat
    hostname: webgoat
    networks:
      vulnerableNet:
        ipv4_address: 172.16.20.140
    ports:
      - "8080:8080"
      - "9090:9090"
    command: bash
    tty: true
    stdin_open: true
    environment:
      TZ: Europe/Amsterdam
#    restart: unless-stopped

  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    ports:
      - 8037:80
#    restart: unless-stopped

networks:
  vulnerableNet:
    ipam:
      config:
        - subnet: 172.16.20.0/24

